export const allFoodsInfo = [{
        id: 0,
        name: 'Marghrita pizza',
        price: 5.50,
        category: 'Pizza',
        orderQuantity: 125,
        rate: 4.5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/0.jpg',
    },
    {
        id: 1,
        name: 'Peppeoni pizza',
        price: 7.50,
        category: 'Pizza',
        orderQuantity: 205,
        rate: 5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/1.jpg',
    },
    {
        id: 2,
        name: 'Garlic and steak pizza',
        price: 9.50,
        category: 'Pizza',
        orderQuantity: 177,
        rate: 4.5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/2.jpg',
    },
    {
        id: 3,
        name: 'Extra cheese pizza',
        price: 6.50,
        category: 'Pizza',
        orderQuantity: 144,
        rate: 4,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/3.jpg',
    },
    {
        id: 4,
        name: 'Hawaiian pizza',
        price: 7.50,
        category: 'Pizza',
        orderQuantity: 103,
        rate: 3.5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/4.jpg',
    },
    {
        id: 5,
        name: 'Meat lover pizza',
        price: 8.50,
        category: 'Pizza',
        orderQuantity: 200,
        rate: 5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/5.jpg',
    },
    {
        id: 6,
        name: 'BBQ chicken pizza',
        price: 7.00,
        category: 'Pizza',
        orderQuantity: 163,
        rate: 4,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/6.jpg',
    },
    {
        id: 7,
        name: 'Lasgne',
        price: 7.00,
        category: 'Pasta',
        orderQuantity: 209,
        rate: 4.5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/7.jpg',
    },
    {
        id: 8,
        name: 'Carbonara pasta',
        price: 6.00,
        category: 'Pasta',
        orderQuantity: 113,
        rate: 5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/8.jpg',
    },
    {
        id: 9,
        name: 'Chicken alfredo pasta',
        price: 7.00,
        category: 'Pasta',
        orderQuantity: 233,
        rate: 4,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/9.jpg',
    },
    {
        id: 10,
        name: 'Pesto pasta',
        price: 5.00,
        category: 'Pasta',
        orderQuantity: 89,
        rate: 3,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/10.jpg',
    },
    {
        id: 11,
        name: 'Bolognese pasta',
        price: 5.50,
        category: 'Pasta',
        orderQuantity: 67,
        rate: 3.5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/11.jpg',
    },
    {
        id: 12,
        name: 'Double burger',
        price: 7.00,
        category: 'Burger',
        orderQuantity: 301,
        rate: 4,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/12.jpg',
    },
    {
        id: 13,
        name: 'Cheese burger',
        price: 6.00,
        category: 'Burger',
        orderQuantity: 333,
        rate: 4,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/13.jpg',
    },
    {
        id: 14,
        name: 'Mushroom burger',
        price: 6.50,
        category: 'Burger',
        orderQuantity: 193,
        rate: 3.5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/14.jpg',
    },
    {
        id: 15,
        name: 'Royal burger',
        price: 8.50,
        category: 'Burger',
        orderQuantity: 163,
        rate: 4,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/15.jpg',
    },
    {
        id: 16,
        name: 'Jalapeno burger',
        price: 6.50,
        category: 'Burger',
        orderQuantity: 203,
        rate: 3,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/16.jpg',
    },
    {
        id: 17,
        name: 'Chicken burger',
        price: 6.00,
        category: 'Burger',
        orderQuantity: 267,
        rate: 4.5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/17.jpg',
    },
    {
        id: 18,
        name: 'Hawaiian burger',
        price: 7.50,
        category: 'Burger',
        orderQuantity: 117,
        rate: 2.5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/18.jpg',
    },
    {
        id: 19,
        name: 'Spicy fried chicken',
        price: 5.50,
        category: 'Fried',
        orderQuantity: 197,
        rate: 3.5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/19.jpg',
    },
    {
        id: 20,
        name: 'Normal fried chicken',
        price: 5.50,
        category: 'Fried',
        orderQuantity: 214,
        rate: 3,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/20.jpg',
    },
    {
        id: 21,
        name: 'Fried wings',
        price: 5.00,
        category: 'Fried',
        orderQuantity: 188,
        rate: 3.5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/21.jpg',
    },
    {
        id: 22,
        name: 'Fried mushrooms',
        price: 3.50,
        category: 'Fried',
        orderQuantity: 142,
        rate: 4.5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/22.jpg',
    },
    {
        id: 23,
        name: 'Fried onions',
        price: 3.00,
        category: 'Fried',
        orderQuantity: 137,
        rate: 2.5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/23.jpg',
    },
    {
        id: 24,
        name: 'Fried potatoes',
        price: 3.00,
        category: 'Fried',
        orderQuantity: 212,
        rate: 3.5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/24.jpg',
    },
    {
        id: 25,
        name: 'Fried shrimps',
        price: 8.50,
        category: 'Fried',
        orderQuantity: 92,
        rate: 4.5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/25.jpg',
    },
    {
        id: 26,
        name: 'Taco',
        price: 2.50,
        category: 'Other',
        orderQuantity: 388,
        rate: 4,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/26.jpg',
    },
    {
        id: 27,
        name: 'French fries',
        price: 2.50,
        category: 'Other',
        orderQuantity: 423,
        rate: 3.5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/27.jpg',
    },
    {
        id: 28,
        name: 'Sushi',
        price: 5.50,
        category: 'Other',
        orderQuantity: 218,
        rate: 4.5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        image: '/Images/foods/28.jpg',
    },
    {
        id: 29,
        name: 'Samosa',
        price: 2.00,
        category: 'Other',
        orderQuantity: 195,
        rate: 4,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/29.jpg',
    },
    {
        id: 30,
        name: 'Hummus',
        price: 3.50,
        category: 'Other',
        orderQuantity: 160,
        rate: 4,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/30.jpg',
    },
    {
        id: 31,
        name: 'Steak',
        price: 10.50,
        category: 'Other',
        orderQuantity: 130,
        rate: 5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/31.jpg',
    },
    {
        id: 32,
        name: 'Hot wings',
        price: 4.50,
        category: 'Other',
        orderQuantity: 180,
        rate: 3.5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/32.jpg',
    },
    {
        id: 33,
        name: 'Hot dog',
        price: 3.00,
        category: 'Other',
        orderQuantity: 298,
        rate: 3.5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/33.jpg',
    },
    {
        id: 34,
        name: 'Caesar salad',
        price: 6.00,
        category: 'Salad',
        orderQuantity: 148,
        rate: 5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/34.jpg',
    },
    {
        id: 35,
        name: 'Bean salad',
        price: 4.00,
        category: 'Salad',
        orderQuantity: 58,
        rate: 3,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/35.jpg',
    },
    {
        id: 36,
        name: 'Greek salad',
        price: 4.50,
        category: 'Salad',
        orderQuantity: 51,
        rate: 4,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/36.jpg',
    },
    {
        id: 37,
        name: 'Caprese salad',
        price: 4.00,
        category: 'Salad',
        orderQuantity: 21,
        rate: 2,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/37.jpg',
    },
    {
        id: 38,
        name: 'Water',
        price: 1.00,
        category: 'Drink',
        orderQuantity: 589,
        rate: 5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/38.jpg',
    },
    {
        id: 39,
        name: 'Soda',
        price: 1.50,
        category: 'Drink',
        orderQuantity: 679,
        rate: 5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/39.jpg',
    },
    {
        id: 40,
        name: 'Lemonade',
        price: 1.50,
        category: 'Drink',
        orderQuantity: 219,
        rate: 4,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/40.jpg',
    },
    {
        id: 41,
        name: 'Orange juice',
        price: 3.50,
        category: 'Drink',
        orderQuantity: 149,
        rate: 5,
        isItInFav: false,
        isItInCart: false,
        deleted: false,
        cartQuantity: 1,
        image: '/Images/foods/41.jpg',
    },
]